s1 = set(input())
s2 = set(input())
print('Common: ' + str(s1.intersection(s2)))
print('Only s1 or s2: ' + str(s1.union(s2).difference(s1.intersection(s2))))
print('Both: ' + str(s1.union(s2)))
print('Only s1: ' + str(s1.difference(s2)))
